2023-07-12 13:55:33.385 -03:00 [ERR] Ocurrio un error en CreateProduct: No tiene rol Administrador
2023-07-12 14:17:03.498 -03:00 [ERR] Ocurrio un error en CreateProduct: System.Exception: No tiene rol Administrador
   at CafeteriaAPI.Controllers.ProductsController.CreateProduct(ProductViewModel producto) in C:\Users\matia\Desktop\TPI-Programacion3\AplicacionWeb\CafeteriaAPI\Controllers\ProductsController.cs:line 67
2023-07-12 14:17:38.348 -03:00 [ERR] Ocurrio un error en GetUserList: No tiene rol Administrador
2023-07-12 14:19:13.435 -03:00 [ERR] Ocurrio un error en CreateRecord: Sequence contains no elements
2023-07-12 14:33:17.288 -03:00 [ERR] Ocurrio un error en GetUserList: No tiene rol Administrador
2023-07-12 14:35:11.686 -03:00 [ERR] Ocurrio un error en CreateRecord: Necesita registrarse para realizar una compra
2023-07-12 14:37:31.594 -03:00 [ERR] Ocurrio un error en GetSaleById: Sequence contains no elements
2023-07-12 17:29:20.011 -03:00 [ERR] Ocurrio un error en CreateRecord: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at lambda_method117(Closure , QueryContext )
   at System.Linq.Queryable.First[TSource](IQueryable`1 source, Expression`1 predicate)
   at Service.Services.SalesService.CreateRecord(SalesViewModel producto) in C:\Users\matia\Desktop\TPI-Programacion3\AplicacionWeb\Service\Services\SalesService.cs:line 32
   at CafeteriaAPI.Controllers.SalesHistoryController.CreateRecord(SalesViewModel record) in C:\Users\matia\Desktop\TPI-Programacion3\AplicacionWeb\CafeteriaAPI\Controllers\SalesHistoryController.cs:line 52
2023-07-12 17:30:16.054 -03:00 [ERR] Ocurrio un error en CreateRecord: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at lambda_method119(Closure , QueryContext )
   at System.Linq.Queryable.First[TSource](IQueryable`1 source, Expression`1 predicate)
   at Service.Services.SalesService.CreateRecord(SalesViewModel producto) in C:\Users\matia\Desktop\TPI-Programacion3\AplicacionWeb\Service\Services\SalesService.cs:line 33
   at CafeteriaAPI.Controllers.SalesHistoryController.CreateRecord(SalesViewModel record) in C:\Users\matia\Desktop\TPI-Programacion3\AplicacionWeb\CafeteriaAPI\Controllers\SalesHistoryController.cs:line 52
2023-07-12 17:39:55.209 -03:00 [ERR] Failed executing DbCommand (0ms) [Parameters=[@p0='?' (Size = 250), @p1='?' (Size = 250), @p2='?' (Size = 250), @p3='?' (DbType = Int32)], CommandType='"Text"', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [Users] ([Email], [Name], [Pass], [RoleId])
VALUES (@p0, @p1, @p2, @p3);
SELECT [UserId]
FROM [Users]
WHERE @@ROWCOUNT = 1 AND [UserId] = scope_identity();
2023-07-12 17:39:55.359 -03:00 [ERR] An exception occurred in the database while saving changes for context type 'Model.Models.CafeteriaContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): The INSERT statement conflicted with the FOREIGN KEY constraint "FK__Users__RoleId__3B75D760". The conflict occurred in database "Cafeteria", table "dbo.RoleList", column 'id'.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
ClientConnectionId:a721c008-acb1-4e48-b079-c613a16b11b9
Error Number:547,State:0,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): The INSERT statement conflicted with the FOREIGN KEY constraint "FK__Users__RoleId__3B75D760". The conflict occurred in database "Cafeteria", table "dbo.RoleList", column 'id'.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
ClientConnectionId:a721c008-acb1-4e48-b079-c613a16b11b9
Error Number:547,State:0,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
2023-07-12 17:39:55.515 -03:00 [ERR] Ocurrio un error en CreateUser: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): The INSERT statement conflicted with the FOREIGN KEY constraint "FK__Users__RoleId__3B75D760". The conflict occurred in database "Cafeteria", table "dbo.RoleList", column 'id'.
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
ClientConnectionId:a721c008-acb1-4e48-b079-c613a16b11b9
Error Number:547,State:0,Class:16
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Service.Services.AuthService.CrearUsuario(UserViewModel User) in C:\Users\matia\Desktop\TPI-Programacion3\AplicacionWeb\Service\Services\AuthService.cs:line 53
   at CafeteriaAPI.Controllers.UserController.CreateUsuario(UserViewModel usuario) in C:\Users\matia\Desktop\TPI-Programacion3\AplicacionWeb\CafeteriaAPI\Controllers\UserController.cs:line 36
2023-07-12 17:47:44.561 -03:00 [ERR] Ocurrio un error en CreateRecord: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at lambda_method203(Closure , QueryContext )
   at System.Linq.Queryable.First[TSource](IQueryable`1 source, Expression`1 predicate)
   at Service.Services.SalesService.CreateRecord(SalesViewModel producto) in C:\Users\matia\Desktop\TPI-Programacion3\AplicacionWeb\Service\Services\SalesService.cs:line 33
   at CafeteriaAPI.Controllers.SalesHistoryController.CreateRecord(SalesViewModel record) in C:\Users\matia\Desktop\TPI-Programacion3\AplicacionWeb\CafeteriaAPI\Controllers\SalesHistoryController.cs:line 52
2023-07-12 17:59:33.610 -03:00 [ERR] Ocurrio un error en GetUserById: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at lambda_method304(Closure , QueryContext )
   at System.Linq.Queryable.First[TSource](IQueryable`1 source, Expression`1 predicate)
   at Service.Services.UserService.GetUserById(Int32 id) in C:\Users\matia\Desktop\TPI-Programacion3\AplicacionWeb\Service\Services\UserService.cs:line 75
   at CafeteriaAPI.Controllers.UserController.GetUsuarioById(Int32 id) in C:\Users\matia\Desktop\TPI-Programacion3\AplicacionWeb\CafeteriaAPI\Controllers\UserController.cs:line 97
